apiVersion: v1
kind: ReplicationController
metadata:
  name: myweb-rc
spec:
  replicas: 3
  selector:
    env: testing
  template:
    metadata:
     name: myweb-pod
     labels:
       env: testing
    spec:
      containers:
      - name: myweb-con
        image: httpd